package com.demo.common.model;

import com.demo.common.model.base.BaseAServerRoutes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AServerRoutes extends BaseAServerRoutes<AServerRoutes> {
	public static final AServerRoutes dao = new AServerRoutes().dao();
}
