package com.demo.common.model;

import com.demo.common.model.base.BaseAServerList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AServerList extends BaseAServerList<AServerList> {
	public static final AServerList dao = new AServerList().dao();
}
