package com.demo.common.model;

import com.demo.common.model.base.BaseDimmenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dimmenu extends BaseDimmenu<Dimmenu> {
	public static final Dimmenu dao = new Dimmenu().dao();
}
