package com.demo.common.model;

import com.demo.common.model.base.BaseDimuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dimuser extends BaseDimuser<Dimuser> {
	public static final Dimuser dao = new Dimuser().dao();
}
