package com.demo.common.model;

import com.demo.common.model.base.BaseJizhanlist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jizhanlist extends BaseJizhanlist<Jizhanlist> {
	public static final Jizhanlist dao = new Jizhanlist().dao();
}
