package com.demo.common.model;

import com.demo.common.model.base.BaseJiZhanXinTiao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JiZhanXinTiao extends BaseJiZhanXinTiao<JiZhanXinTiao> {
	public static final JiZhanXinTiao dao = new JiZhanXinTiao().dao();
}
