package com.demo.common.model;

import com.demo.common.model.base.BaseJizhanpara;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Jizhanpara extends BaseJizhanpara<Jizhanpara> {
	public static final Jizhanpara dao = new Jizhanpara().dao();
}
