package com.demo.common.model;

import com.demo.common.model.base.BaseNServerRoutes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NServerRoutes extends BaseNServerRoutes<NServerRoutes> {
	public static final NServerRoutes dao = new NServerRoutes().dao();
}
