package com.demo.common.model;

import com.demo.common.model.base.BaseNServerList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NServerList extends BaseNServerList<NServerList> {
	public static final NServerList dao = new NServerList().dao();
}
