package com.demo.common.model;

import com.demo.common.model.base.BaseNSServerPara;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NSServerPara extends BaseNSServerPara<NSServerPara> {
	public static final NSServerPara dao = new NSServerPara().dao();
}
