package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDimmenu<M extends BaseDimmenu<M>> extends Model<M> implements IBean {

	public M setMenuID(java.lang.Integer MenuID) {
		set("MenuID", MenuID);
		return (M)this;
	}
	
	public java.lang.Integer getMenuID() {
		return getInt("MenuID");
	}

	public M setMenuName(java.lang.String MenuName) {
		set("MenuName", MenuName);
		return (M)this;
	}
	
	public java.lang.String getMenuName() {
		return getStr("MenuName");
	}

	public M setMenuPath(java.lang.String MenuPath) {
		set("MenuPath", MenuPath);
		return (M)this;
	}
	
	public java.lang.String getMenuPath() {
		return getStr("MenuPath");
	}

	public M setMenuType(java.lang.Integer MenuType) {
		set("MenuType", MenuType);
		return (M)this;
	}
	
	public java.lang.Integer getMenuType() {
		return getInt("MenuType");
	}

	public M setVisible(java.lang.Integer Visible) {
		set("Visible", Visible);
		return (M)this;
	}
	
	public java.lang.Integer getVisible() {
		return getInt("Visible");
	}

	public M setOrderBy(java.lang.Integer OrderBy) {
		set("OrderBy", OrderBy);
		return (M)this;
	}
	
	public java.lang.Integer getOrderBy() {
		return getInt("OrderBy");
	}

	public M setActive(java.lang.Integer Active) {
		set("Active", Active);
		return (M)this;
	}
	
	public java.lang.Integer getActive() {
		return getInt("Active");
	}

}
