package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJiZhanXinTiao<M extends BaseJiZhanXinTiao<M>> extends Model<M> implements IBean {

	public M setEUI(java.lang.Integer EUI) {
		set("EUI", EUI);
		return (M)this;
	}
	
	public java.lang.Integer getEUI() {
		return getInt("EUI");
	}

	public M setIP(java.lang.String IP) {
		set("IP", IP);
		return (M)this;
	}
	
	public java.lang.String getIP() {
		return getStr("IP");
	}

	public M setNetID(java.lang.String NetID) {
		set("NetID", NetID);
		return (M)this;
	}
	
	public java.lang.String getNetID() {
		return getStr("NetID");
	}

	public M setNBroker(java.lang.String NBroker) {
		set("NBroker", NBroker);
		return (M)this;
	}
	
	public java.lang.String getNBroker() {
		return getStr("NBroker");
	}

	public M setLati(java.lang.String Lati) {
		set("Lati", Lati);
		return (M)this;
	}
	
	public java.lang.String getLati() {
		return getStr("Lati");
	}

	public M setLongti(java.lang.String Longti) {
		set("Longti", Longti);
		return (M)this;
	}
	
	public java.lang.String getLongti() {
		return getStr("Longti");
	}

	public M setDeviceHandle(java.lang.String DeviceHandle) {
		set("DeviceHandle", DeviceHandle);
		return (M)this;
	}
	
	public java.lang.String getDeviceHandle() {
		return getStr("DeviceHandle");
	}

	public M setHardwareversion(java.lang.String Hardwareversion) {
		set("Hardwareversion", Hardwareversion);
		return (M)this;
	}
	
	public java.lang.String getHardwareversion() {
		return getStr("Hardwareversion");
	}

	public M setFirmwareversion(java.lang.String Firmwareversion) {
		set("Firmwareversion", Firmwareversion);
		return (M)this;
	}
	
	public java.lang.String getFirmwareversion() {
		return getStr("Firmwareversion");
	}

	public M setStatus(java.lang.String Status) {
		set("Status", Status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("Status");
	}

	public M setRxPackets(java.lang.String RxPackets) {
		set("RxPackets", RxPackets);
		return (M)this;
	}
	
	public java.lang.String getRxPackets() {
		return getStr("RxPackets");
	}

	public M setTxPackets(java.lang.String TxPackets) {
		set("TxPackets", TxPackets);
		return (M)this;
	}
	
	public java.lang.String getTxPackets() {
		return getStr("TxPackets");
	}

}
