package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNSServerPara<M extends BaseNSServerPara<M>> extends Model<M> implements IBean {

	public M setSN(java.lang.Integer SN) {
		set("SN", SN);
		return (M)this;
	}
	
	public java.lang.Integer getSN() {
		return getInt("SN");
	}

	public M setNsNwkid(java.lang.String nsNwkid) {
		set("ns_nwkid", nsNwkid);
		return (M)this;
	}
	
	public java.lang.String getNsNwkid() {
		return getStr("ns_nwkid");
	}

	public M setNsNetid(java.lang.String nsNetid) {
		set("ns_netid", nsNetid);
		return (M)this;
	}
	
	public java.lang.String getNsNetid() {
		return getStr("ns_netid");
	}

	public M setNsName(java.lang.String nsName) {
		set("ns_name", nsName);
		return (M)this;
	}
	
	public java.lang.String getNsName() {
		return getStr("ns_name");
	}

	public M setNsBroker(java.lang.String nsBroker) {
		set("ns_broker", nsBroker);
		return (M)this;
	}
	
	public java.lang.String getNsBroker() {
		return getStr("ns_broker");
	}

	public M setNsBrokeraccount(java.lang.String nsBrokeraccount) {
		set("ns_brokerAccount", nsBrokeraccount);
		return (M)this;
	}
	
	public java.lang.String getNsBrokeraccount() {
		return getStr("ns_brokerAccount");
	}

	public M setNsJoinDelay(java.lang.String nsJoinDelay) {
		set("ns_join_delay", nsJoinDelay);
		return (M)this;
	}
	
	public java.lang.String getNsJoinDelay() {
		return getStr("ns_join_delay");
	}

	public M setNsWindowselect(java.lang.String nsWindowselect) {
		set("ns_windowselect", nsWindowselect);
		return (M)this;
	}
	
	public java.lang.String getNsWindowselect() {
		return getStr("ns_windowselect");
	}

}
