package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDimuser<M extends BaseDimuser<M>> extends Model<M> implements IBean {

	public M setUserID(java.lang.Integer UserID) {
		set("UserID", UserID);
		return (M)this;
	}
	
	public java.lang.Integer getUserID() {
		return getInt("UserID");
	}

	public M setRoleID(java.lang.Integer RoleID) {
		set("RoleID", RoleID);
		return (M)this;
	}
	
	public java.lang.Integer getRoleID() {
		return getInt("RoleID");
	}

	public M setLoginName(java.lang.String LoginName) {
		set("LoginName", LoginName);
		return (M)this;
	}
	
	public java.lang.String getLoginName() {
		return getStr("LoginName");
	}

	public M setPassWord(java.lang.String PassWord) {
		set("PassWord", PassWord);
		return (M)this;
	}
	
	public java.lang.String getPassWord() {
		return getStr("PassWord");
	}

	public M setRealName(java.lang.String RealName) {
		set("RealName", RealName);
		return (M)this;
	}
	
	public java.lang.String getRealName() {
		return getStr("RealName");
	}

	public M setEmail(java.lang.String Email) {
		set("Email", Email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("Email");
	}

	public M setCellPhon(java.lang.String CellPhon) {
		set("CellPhon", CellPhon);
		return (M)this;
	}
	
	public java.lang.String getCellPhon() {
		return getStr("CellPhon");
	}

}
