package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAServerRoutes<M extends BaseAServerRoutes<M>> extends Model<M> implements IBean {

	public M setAppeui(java.lang.Integer appeui) {
		set("appeui", appeui);
		return (M)this;
	}
	
	public java.lang.Integer getAppeui() {
		return getInt("appeui");
	}

	public M setAppKey(java.lang.String AppKey) {
		set("AppKey", AppKey);
		return (M)this;
	}
	
	public java.lang.String getAppKey() {
		return getStr("AppKey");
	}

	public M setNwkKey(java.lang.String NwkKey) {
		set("NwkKey", NwkKey);
		return (M)this;
	}
	
	public java.lang.String getNwkKey() {
		return getStr("NwkKey");
	}

	public M setAsCsBroker(java.lang.String asCsBroker) {
		set("as_cs_broker", asCsBroker);
		return (M)this;
	}
	
	public java.lang.String getAsCsBroker() {
		return getStr("as_cs_broker");
	}

	public M setAsCsAccount(java.lang.String asCsAccount) {
		set("as_cs_account", asCsAccount);
		return (M)this;
	}
	
	public java.lang.String getAsCsAccount() {
		return getStr("as_cs_account");
	}

	public M setAsProtocolmode(java.lang.String asProtocolmode) {
		set("as_protocolmode", asProtocolmode);
		return (M)this;
	}
	
	public java.lang.String getAsProtocolmode() {
		return getStr("as_protocolmode");
	}

	public M setAsRxdelay(java.lang.String asRxdelay) {
		set("as_rxdelay", asRxdelay);
		return (M)this;
	}
	
	public java.lang.String getAsRxdelay() {
		return getStr("as_rxdelay");
	}

	public M setAsRx1droffet(java.lang.String asRx1droffet) {
		set("as_rx1droffet", asRx1droffet);
		return (M)this;
	}
	
	public java.lang.String getAsRx1droffet() {
		return getStr("as_rx1droffet");
	}

	public M setAsRx2dr(java.lang.String asRx2dr) {
		set("as_rx2dr", asRx2dr);
		return (M)this;
	}
	
	public java.lang.String getAsRx2dr() {
		return getStr("as_rx2dr");
	}

	public M setAsRx2freq(java.lang.String asRx2freq) {
		set("as_rx2freq", asRx2freq);
		return (M)this;
	}
	
	public java.lang.String getAsRx2freq() {
		return getStr("as_rx2freq");
	}

	public M setAsCflistStatus(java.lang.String asCflistStatus) {
		set("as_cflist_status", asCflistStatus);
		return (M)this;
	}
	
	public java.lang.String getAsCflistStatus() {
		return getStr("as_cflist_status");
	}

	public M setAsCflist4(java.lang.String asCflist4) {
		set("as_cflist4", asCflist4);
		return (M)this;
	}
	
	public java.lang.String getAsCflist4() {
		return getStr("as_cflist4");
	}

	public M setAsCflist5(java.lang.String asCflist5) {
		set("as_cflist5", asCflist5);
		return (M)this;
	}
	
	public java.lang.String getAsCflist5() {
		return getStr("as_cflist5");
	}

	public M setAsCflist6(java.lang.String asCflist6) {
		set("as_cflist6", asCflist6);
		return (M)this;
	}
	
	public java.lang.String getAsCflist6() {
		return getStr("as_cflist6");
	}

	public M setAsCflist7(java.lang.String asCflist7) {
		set("as_cflist7", asCflist7);
		return (M)this;
	}
	
	public java.lang.String getAsCflist7() {
		return getStr("as_cflist7");
	}

	public M setAsRfu(java.lang.String asRfu) {
		set("as_rfu", asRfu);
		return (M)this;
	}
	
	public java.lang.String getAsRfu() {
		return getStr("as_rfu");
	}

}
