package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNServerRoutes<M extends BaseNServerRoutes<M>> extends Model<M> implements IBean {

	public M setAppeui(java.lang.Integer appeui) {
		set("appeui", appeui);
		return (M)this;
	}
	
	public java.lang.Integer getAppeui() {
		return getInt("appeui");
	}

	public M setAserverIp(java.lang.String aserverIp) {
		set("aserver_ip", aserverIp);
		return (M)this;
	}
	
	public java.lang.String getAserverIp() {
		return getStr("aserver_ip");
	}

	public M setAserverPort(java.lang.String aserverPort) {
		set("aserver_port", aserverPort);
		return (M)this;
	}
	
	public java.lang.String getAserverPort() {
		return getStr("aserver_port");
	}

	public M setNsDnPreamble(java.lang.String nsDnPreamble) {
		set("ns_dn_preamble", nsDnPreamble);
		return (M)this;
	}
	
	public java.lang.String getNsDnPreamble() {
		return getStr("ns_dn_preamble");
	}

	public M setNsPower(java.lang.String nsPower) {
		set("ns_power", nsPower);
		return (M)this;
	}
	
	public java.lang.String getNsPower() {
		return getStr("ns_power");
	}

	public M setNsBcnSlotlen(java.lang.String nsBcnSlotlen) {
		set("ns_bcn_slotlen", nsBcnSlotlen);
		return (M)this;
	}
	
	public java.lang.String getNsBcnSlotlen() {
		return getStr("ns_bcn_slotlen");
	}

	public M setNsBcnGuard(java.lang.String nsBcnGuard) {
		set("ns_bcn_guard", nsBcnGuard);
		return (M)this;
	}
	
	public java.lang.String getNsBcnGuard() {
		return getStr("ns_bcn_guard");
	}

	public M setNsBcnFreq(java.lang.String nsBcnFreq) {
		set("ns_bcn_freq", nsBcnFreq);
		return (M)this;
	}
	
	public java.lang.String getNsBcnFreq() {
		return getStr("ns_bcn_freq");
	}

	public M setNsBcnReserved(java.lang.String nsBcnReserved) {
		set("ns_bcn_reserved", nsBcnReserved);
		return (M)this;
	}
	
	public java.lang.String getNsBcnReserved() {
		return getStr("ns_bcn_reserved");
	}

	public M setNsBcnPeriod(java.lang.String nsBcnPeriod) {
		set("ns_bcn_period", nsBcnPeriod);
		return (M)this;
	}
	
	public java.lang.String getNsBcnPeriod() {
		return getStr("ns_bcn_period");
	}

	public M setNsAdrHighmargin(java.lang.String nsAdrHighmargin) {
		set("ns_adr_highMargin", nsAdrHighmargin);
		return (M)this;
	}
	
	public java.lang.String getNsAdrHighmargin() {
		return getStr("ns_adr_highMargin");
	}

	public M setNsAdrLowmargin(java.lang.String nsAdrLowmargin) {
		set("ns_adr_lowMargin", nsAdrLowmargin);
		return (M)this;
	}
	
	public java.lang.String getNsAdrLowmargin() {
		return getStr("ns_adr_lowMargin");
	}

	public M setNsAdrChannelmask(java.lang.String nsAdrChannelmask) {
		set("ns_adr_channelMask", nsAdrChannelmask);
		return (M)this;
	}
	
	public java.lang.String getNsAdrChannelmask() {
		return getStr("ns_adr_channelMask");
	}

	public M setNsAdrRetran(java.lang.String nsAdrRetran) {
		set("ns_adr_Retran", nsAdrRetran);
		return (M)this;
	}
	
	public java.lang.String getNsAdrRetran() {
		return getStr("ns_adr_Retran");
	}

	public M setNsAdrChmaskcnti(java.lang.String nsAdrChmaskcnti) {
		set("ns_adr_ChMaskCnti", nsAdrChmaskcnti);
		return (M)this;
	}
	
	public java.lang.String getNsAdrChmaskcnti() {
		return getStr("ns_adr_ChMaskCnti");
	}

}
