package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAServerList<M extends BaseAServerList<M>> extends Model<M> implements IBean {

	public M setSN(java.lang.Integer SN) {
		set("SN", SN);
		return (M)this;
	}
	
	public java.lang.Integer getSN() {
		return getInt("SN");
	}

	public M setAsName(java.lang.String asName) {
		set("as_name", asName);
		return (M)this;
	}
	
	public java.lang.String getAsName() {
		return getStr("as_name");
	}

	public M setAsNsIp(java.lang.String asNsIp) {
		set("as_ns_ip", asNsIp);
		return (M)this;
	}
	
	public java.lang.String getAsNsIp() {
		return getStr("as_ns_ip");
	}

	public M setAsNsPort(java.lang.String asNsPort) {
		set("as_ns_port", asNsPort);
		return (M)this;
	}
	
	public java.lang.String getAsNsPort() {
		return getStr("as_ns_port");
	}

	public M setAsOverload(java.lang.String asOverload) {
		set("as_overload", asOverload);
		return (M)this;
	}
	
	public java.lang.String getAsOverload() {
		return getStr("as_overload");
	}

	public M setAsUppackets(java.lang.String asUppackets) {
		set("as_uppackets", asUppackets);
		return (M)this;
	}
	
	public java.lang.String getAsUppackets() {
		return getStr("as_uppackets");
	}

	public M setAsUpbytes(java.lang.String asUpbytes) {
		set("as_upbytes", asUpbytes);
		return (M)this;
	}
	
	public java.lang.String getAsUpbytes() {
		return getStr("as_upbytes");
	}

	public M setAsDnpackets(java.lang.String asDnpackets) {
		set("as_dnpackets", asDnpackets);
		return (M)this;
	}
	
	public java.lang.String getAsDnpackets() {
		return getStr("as_dnpackets");
	}

	public M setAsDnbytes(java.lang.String asDnbytes) {
		set("as_dnbytes", asDnbytes);
		return (M)this;
	}
	
	public java.lang.String getAsDnbytes() {
		return getStr("as_dnbytes");
	}

	public M setAsMotecounts(java.lang.String asMotecounts) {
		set("as_motecounts", asMotecounts);
		return (M)this;
	}
	
	public java.lang.String getAsMotecounts() {
		return getStr("as_motecounts");
	}

	public M setAsActivemotes(java.lang.String asActivemotes) {
		set("as_activemotes", asActivemotes);
		return (M)this;
	}
	
	public java.lang.String getAsActivemotes() {
		return getStr("as_activemotes");
	}

}
